name: CI

on:
  push:
#    branches:
#      - master
  pull_request:
    branches:
      - master

jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        env:
          - {CI_NAME: focal,
             OS_NAME: ubuntu,
             OS_CODE_NAME: focal,
             ROS_DISTRO: foxy,
             ROS_REPO: main,
             DOCKER_IMAGE: "ros:foxy"}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
